### ISSUE TITLE
Game continues even after winning Battle Mode

### ISSUE THREAD

**Issue by Thewimo** [sstokic-tgm/JFTSE#1]
- Won against NPC in Battle Mode
- NPC dead, vistory screen shows
- Guardian continues serving on both sides
- Can't replicate this one
- However character can still move and take damage in victory screen

**Comment by sstokic-tgm** [comment]
Are you sure about your third point? Testing it locally didn't give me that behaviour :/

**Comment by sstokic-tgm** [comment]
Fixed with commit: 2156662
