### ISSUE TITLE
4002,-62

### ISSUE THREAD

**Issue by ck17489** [sstokic-tgm/JFTSE#107]
4002,-62
![1623107419072](https://user-images.githubusercontent.com/85529783/121100541-b2464d00-c82c-11eb-980e-d2560658c6c6.jpg)

How can I fix it QAQ

**Comment by milov-afk** [comment]
You should check firstly the #faq section on the Discord server. There are explained most of the cases and how to fix them.

**Comment by ck17489** [comment]
OKAY~

**Comment by sstokic-tgm** [comment]
The issue is not directly related to this project but to the anticheat, therefore I will close this and see you in discord :)
