### ISSUE TITLE
Right now, the guardian mode vs. battle and basic solo mode has issues.

### ISSUE THREAD

**Issue by champ30975** [sstokic-tgm/JFTSE#109]
Please download and watch my video and come to check.
Thank 
[https://drive.google.com/file/d/1pkmX-RjZVTmquOHRvnZ9rl3nur3WZ-Ub/view?usp=sharing](url)

**Comment by champ30975** [comment]
@

- [ ]

**Comment by sstokic-tgm** [comment]
That day the server was laging, so this is quite possible when this happens. Does it still persist and if yes I hope for now not often 👍

**Comment by champ30975** [comment]
No problem now, thank you.

**Comment by champ30975** [comment]
Fanta tennis server closed permanently?

**Comment by killerzxn** [comment]
> Fanta tennis server closed permanently?

No, the server is down for a maintance, so just be patience
