### ISSUE TITLE
The user is blocked.

### ISSUE THREAD

**Issue by Kratuaza** [sstokic-tgm/JFTSE#114]
I don't know why my user id is blocked, could you check pls,

user id is : kratuaza

Thank you for your help.

**Comment by sstokic-tgm** [comment]
You were banned automatically by our detection system for QS using.
[15:25:46,161] Kratuaza died because of no QS CD hack. Marked for ban.

Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.

**Comment by Kratuaza** [comment]
How to unblock ?

**Comment by sstokic-tgm** [comment]
You have been banned for hacking, therefore it's not possible. Please don't use hacks and as I said, refer to discord for this kind of requests/questions
