### ISSUE TITLE
The user is blocked

### ISSUE THREAD

**Issue by AbbyKanon** [sstokic-tgm/JFTSE#117]
don't know why my user id is blocked, could you check pls,

user id is : abby

Thank you for your help.and i dont use hacking more ,you can ask heng,just bug show i QS no CD just one time ,and my id block
but i dont use hacing,why

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks. By now your account is unbanned
