### ISSUE TITLE
[Question] Start application.

### ISSUE THREAD

**Issue by jcs090218** [sstokic-tgm/JFTSE#12]
Just one quick question, how did you start the application? Sorry that I am not very familiar to Spring framework. Once I got the following output; the application seems to be stopped! 😕 

```
23:19:57,155 [main] INFO  Starting StartApplication on DESKTOP-KVGQGUF with PID 29032 (C:\path\to\project\JFTSE\target\classes started by JenChieh in C:\path\to\project\JFTSE)
23:19:57,160 [main] DEBUG Running with Spring Boot v2.1.12.RELEASE, Spring v5.1.13.RELEASE
23:19:57,161 [main] INFO  No active profile set, falling back to default profiles: default
```

**Comment by sstokic-tgm** [comment]
Hey, normally that part is shown for a few seconds (like up to 15s) after that the rest comes.
In your case it hangs there or how? If yes, to see more output, change these things to "on" inside application.properties (which is located in src/main/resources):
logging.level.org.springframework
logging.level.root
spring.main.banner-mode

You will see more output anf if something fails, you gonna see some error or warn messages which can help you out

**Comment by jcs090218** [comment]
I just realized this! Thanks! Close this issue now!
