### ISSUE TITLE
Is it normal that I cannot log in to my account?

### ISSUE THREAD

**Issue by s16amy** [sstokic-tgm/JFTSE#121]
I cannot login into the game anymore since it says "your ID is invalid."

**Comment by Velucy** [comment]
please update your account on jftse.com, visit the discord for more information and help.

**Comment by s16amy** [comment]
I only remember my account password, I forgot my mailbox😭

**Comment by s16amy** [comment]
Hope can help me
I only remember my account password, I forgot my mailbox
Could not update account

MY user id is : mimi

Please let me know if you need more information
Tthank you😭

**Comment by s16amy** [comment]
I tried to log in successfully
Thank you for helping ❤

**Comment by abc123-168** [comment]
我也遇到同一樣問題好幾天沒辦法進入遊戲
