### ISSUE TITLE
Problème de connexion

### ISSUE THREAD

**Issue by Danphux** [sstokic-tgm/JFTSE#129]
Bonjour,

Voulant mettre mon compte à jour pour pouvoir jouer à nouveau, je rencontre un problème.
Mon mot de passe est trop long et je n'arrive pas à le modifier.
Pouvez vous m'aider s'il vous plait?

Merci d'avance.

**Comment by killerzxn** [comment]
S'il vous plaît, rejoignez notre serveur discord et créez un ticket pour vous aider.
https://discord.gg/RBTG59jH8F
