### ISSUE TITLE
Can not connect gameserver (using refactor-dev)

### ISSUE THREAD

**Issue by sarasagbf** [sstokic-tgm/JFTSE#141]
![charactor selection](https://user-images.githubusercontent.com/40536261/155873203-24adab91-cf16-4491-a012-4939bbbf7d3e.png)
[stacktrace.txt](https://github.com/sstokic-tgm/JFTSE/files/8148276/stacktrace.txt)

I used [refactor-dev] to start the server.
However, I got an error message on the screen when create a character for the first time after logging in.
The log output to the server at that time is attached.
I would like to know if there is a solution.
thank you.

**Comment by sstokic-tgm** [comment]
Pulling the latest commit of refactor-dev will have this issue fixed. 
Commit no.: #4f14583
