### ISSUE TITLE
Could you please bring accessories : Atlantis Moderator back?

### ISSUE THREAD

**Issue by mildysweetza** [sstokic-tgm/JFTSE#142]
![image](https://user-images.githubusercontent.com/101316190/158102472-1abc9c4e-b4a5-4875-9506-c894dfde0053.jpeg)

I known the news that Fanta Tennis   Opened comeback too late and I wish this item so much. It have a chance or not?

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
