### ISSUE TITLE
when I try to log in it shows me a white

### ISSUE THREAD

**Issue by tYLERDURE** [sstokic-tgm/JFTSE#144]
![Screenshot 2022-03-19 183857](https://user-images.githubusercontent.com/101953338/159140844-a1482017-b727-41bc-9855-5ff9111fe9ce.png)

**Comment by tYLERDURE** [comment]
WHAT DO I DO

**Comment by tYLERDURE** [comment]
![Screenshot 2022-03-19 183953](https://user-images.githubusercontent.com/101953338/159140864-5dc3c914-ed24-430b-8b11-d51a7080ae1f.png)

**Comment by sstokic-tgm** [comment]
Was temporary only and nothing to do with the project itself.
