### ISSUE TITLE
Please Check ** Code = 4002, -2 (Fantasy Tennis)

### ISSUE THREAD

**Issue by XMA92** [sstokic-tgm/JFTSE#146]
Hi Dear All Concern,

I have got an issue for the last 2 days until now.
when I log in my ID, It pops up with the error **code = 4002, -2**
the message is ** This user id is currently logged on Please try again later. **

How can I solve this problem?

Thanks

**Comment by leoc1** [comment]
Enter here: jftse.com click in discord join community! Fanta Tennis rebirth, search by #faq

**Comment by XMA92** [comment]
I already posted on Discord #fag Please Help!

**Comment by XMA92** [comment]
Last week It had already solved. but Now It has it again **Error code = 4002, -2** 
What happened to me !!

Pls kindly Help me! Thanks.

**Comment by leoc1** [comment]
What I can tell you is that this is common on the European fantasy tennis server, just open a new ticket to @modmail on discord and they will reset you on game, I believe it is something wrong with the game's programming, but as the team is good I believe firmly that they will solve this problem in the future
