### ISSUE TITLE
Account Problem

### ISSUE THREAD

**Issue by alin0612** [sstokic-tgm/JFTSE#148]
Hi there, 

I haven't been on my account for two days already, but when I tried to log in today, it says the user id is currently logged on.
please double-check this issue.

code: = 4002 -2, 

My Account: alin0612

**Comment by alin0612** [comment]
Game platform:  Fanta Tennis

**Comment by Velucy** [comment]
Hello, are you on discord? If so please open a ticket with "ModMail" there, we will take care of it. Otherwise please relay the character name this happened on, thanks.

**Comment by alin0612** [comment]
Hi, I only have one character inside this account and the character name is called Allsaints

not sure where to find modmail and open a ticket, could you kindly guide me and provide steps?

**Comment by Velucy** [comment]
https://discord.gg/Jyxq7tu4u3

this is the discord, join there for news and other stuff, easier to support as well.

You should be able to login again now.

**Comment by alin0612** [comment]
just log in, thank you!

**Comment by alin0612** [comment]
how come I cant join the discord conversation? it wouldn't allow me to send messages, and i can't see the content as well
My account is happening the same issue again as last time.

**Comment by Velucy** [comment]
you have to accept the rules on the discord server in the #rules channel, otherwise you aren't allowed to post/see anything it's a protection against bots mostly.

**Comment by ldlv587** [comment]
id：nosegod   ，same question，can u help me？the DISCORD cant open so i cant use modmail

**Comment by viol3** [comment]
I resetted your account status, nosegod

**Comment by ldlv587** [comment]
> 

thank u,   u are wonderful guy
