### ISSUE TITLE
wing of memory , it can be exchanged  by coins instead of ap?

### ISSUE THREAD

**Issue by ldlv587** [sstokic-tgm/JFTSE#160]
i have not  played it for so long that i forget how to add stats,so i want to reset stats  by buy wing of memory. but it need 5 ap,i ask many players,they said ap is event currency, an event takes place when christmas,valentinsday,eastern and this stuff. but its too long for me with anxious mood,so may i have gold coins for my request  or whatever is convenient for you please.  my id is nosegod,thanks.

**Comment by viol3** [comment]
"an event takes place when christmas,valentinsday,eastern and this stuff"
who said this, we are making events every months and weeks.

**Comment by ldlv587** [comment]
Thanks for your reply, but I've been playing for almost three weeks and haven't seen any activity in the game. Is it in the DISCORD section? I can't open that DISCORD section.

**Comment by viol3** [comment]
Yes you need to be active in discord, we are making announcement in discord server

**Comment by ldlv587** [comment]
thank u,I can't open discord right now, but I'll try use a ladder

**Comment by ldlv587** [comment]
I went into DISCORD, but I didn't see anything about quest , events or ap, and I didn't have permission to send messages on the channel. Do I need to wait for you to post a quest?

**Comment by viol3** [comment]
which channel you are looking? did you see #jftse-events channel?

**Comment by ldlv587** [comment]
no,i didnt see jftse-event,only faq ,information-news, new-members,and github-feed

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
