### ISSUE TITLE
FT login He keeps saying that this user ID is now being logged in

### ISSUE THREAD

**Issue by suhmoto** [sstokic-tgm/JFTSE#161]
![image](https://user-images.githubusercontent.com/127651896/224530560-d8b056a3-1054-45df-ac5f-c68c914e4101.png)

He keeps saying that this user ID is now being logged in

**Comment by viol3** [comment]
Please send your reports via modmail in discord server. You can send a ticket in modmail with your character name and we will reset the status.

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
