### ISSUE TITLE
He said I can't connect, is there any way to solve it?

### ISSUE THREAD

**Issue by suhmoto** [sstokic-tgm/JFTSE#162]
He said I can't connect, is [there](url) any way to solve it?
![image](https://user-images.githubusercontent.com/127651896/224723127-ae1cff3a-1682-47c1-ab9f-faba45a3e9b1.png)

**Comment by viol3** [comment]
You have to come discord server and create a ticket with modmail about this error.

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
