### ISSUE TITLE
Hi when i run the launcher it shows me an error and i can't download the files to play this eror gives me  [ERROR] Could not get remote checksum file: https://jftse.com/updater/files.md5 

### ISSUE THREAD

**Issue by Mitakuss** [sstokic-tgm/JFTSE#167]
Hi when i run the launcher it shows me an error and i can't download the files to play this eror gives me  [ERROR] Could not get remote checksum file: https://jftse.com/updater/files.md5

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
