### ISSUE TITLE
Game crashes if minimized

### ISSUE THREAD

**Issue by RamHa94** [sstokic-tgm/JFTSE#171]
To reproduce the issue:

1. Start game and login 
2. Minimize the game.
3. Connect in the character selection
4. Wait for 1 minute or 2
5. Go back to the game
![Error](https://github.com/sstokic-tgm/JFTSE/assets/152423567/75a03355-e264-4b8f-9551-39e818110b38)

**Comment by sstokic-tgm** [comment]
This issue is client related. Also since it is an old game things might not work like with the games currently on the market.

Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
