### ISSUE TITLE
error - "user already exist"

### ISSUE THREAD

**Issue by alexandrupop2023** [sstokic-tgm/JFTSE#172]
Hello, I tryied to sign up at JFTSE Fantasy Tensnis and whatever user I wrote, "user already exist" appeared. What should I do? Or do you have a account that u do not use? I m really nostalgic! thx

**Comment by taihiroshima** [comment]
I have this problem too, could anyone help?

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
