### ISSUE TITLE
no puedo entrar al juego usando la ultima version

### ISSUE THREAD

**Issue by hacksign2024** [sstokic-tgm/JFTSE#173]
ya son varias pc q instalo el juego y no me deja entrar pero cuando entro a mi pc de mi casa si puedo jugar alli dice q estoy usando un programa antiguo pero todos los wiindows son acatualizados y ltsc y windows 10 pro y no deja jugar ayuuuda
<img width="960" alt="captura" src="https://github.com/sstokic-tgm/JFTSE/assets/162400159/408ba1f1-58bf-48cf-9bad-1e6163558015">
<img width="960" alt="captura" src="https://github.com/sstokic-tgm/JFTSE/assets/162400159/a8c4c40e-97dd-47f4-aca1-5e3277503a53">

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
