### ISSUE TITLE
Launcher doesn't connect to server

### ISSUE THREAD

**Issue by aciily** [sstokic-tgm/JFTSE#174]
When I start JFTSE normally there isn't any problem. Yes, the server crashes sometimes, but I never had it launching multiple times but never reach to the actual game. The error says "Connection failed to the server". Hopefully this is just a server crash for today, was looking forward to play it today!

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.
