### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by gingerbread-p** [sstokic-tgm/JFTSE#175]
I wanna play on Mac OS ,please 😭

**Comment by killerzxn** [comment]
Fantasy Tennis runs on Mac OS X and other Unix-based OS as well (Although not natively). You need Wine/Wineskin to run it.
More information on how to run it can be found here:
https://github.com/Gcenx/WineskinServer  (Required if you are running Mac OS 10.14+ or have a M1 model)
https://www.winehq.org/ (Linux & Mac OS <10.13)

**Comment by sstokic-tgm** [comment]
Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.

**Comment by gingerbread-p** [comment]
> Fantasy Tennis runs on Mac OS X and other Unix-based OS as well (Although not natively). You need Wine/Wineskin to run it. More information on how to run it can be found here: https://github.com/Gcenx/WineskinServer (Required if you are running Mac OS 10.14+ or have a M1 model) https://www.winehq.org/ (Linux & Mac OS <10.13)

thank you

**Comment by gingerbread-p** [comment]
> Please use the discord for this type of requests/questions, since it's not related to the emulator itself, thanks.

thank you
