### ISSUE TITLE
Implement rules for receiving player

### ISSUE THREAD

**Issue by Davingi** [sstokic-tgm/JFTSE#41]
- Only receiving player is allowed to receive the ball. Otherwise it's a foul
- The receiving player is only allowed to receive the ball when the ball bounced one time. Otherwise it's a foul

**Comment by sstokic-tgm** [comment]
Only receiving player is allowed to receive the ball. Otherwise it's a foul - implemented

**Comment by sstokic-tgm** [comment]
Fixed as of 296bdd9
