### ISSUE TITLE
Basic 1v1 Court Change after a set: Winner cries and Loser laughs

### ISSUE THREAD

**Issue by Thewimo** [sstokic-tgm/JFTSE#44]

**Comment by sstokic-tgm** [comment]
@Thewimo does the issue still exist as of the most recent changes?

**Comment by Thewimo** [comment]
> @Thewimo does the issue still exist as of the most recent changes?

Yes it did. At around 22:00

**Comment by sstokic-tgm** [comment]
Sorry for asking again, but, is it still present?

**Comment by Velucy** [comment]
Issue still present. 
https://imgur.com/gyXqANh

**Comment by Davingi** [comment]
Should be fixed now. Please tell me then if this issue still occurs

**Comment by Velucy** [comment]
seems to still occur, have seen people getting it. Have to test some more to maybe get it myself too

**Comment by Davingi** [comment]
Closing this issue since the bug doesn't seem to occur anymore.
