### ISSUE TITLE
Room crashes if a player leaves after a match

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#47]
If you play a match and someone leaves the room after the match ended, the whole room (usually excluding the one who left so far) will crash

**Comment by Davingi** [comment]
Bug is reproducable when the player leaving the room has a chat bubble

**Comment by Davingi** [comment]
Not closing it until it's confirmed, that this bug is truly fixed.

**Comment by sstokic-tgm** [comment]
Refer this as an addition: 47c1967

**Comment by Velucy** [comment]
Didn't encounter this bug anymore so far. Will report if anything in this direction comes up

**Comment by elmuty24** [comment]
![image](https://user-images.githubusercontent.com/58943878/106178697-dd32dd00-6178-11eb-8210-26ceda5f8742.png)

celebrate even didnt start the game

**Comment by elmuty24** [comment]
and the bug of celebrating even lose is still alive

**Comment by Davingi** [comment]
Closing this issue since the bug doesn't seem to occur anymore.
