### ISSUE TITLE
Players freeze in the middle of a match

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#48]
this happened before from time to time, but I wasn't able to finish a single match since the restart, this bug occurred in every match so far. At least 2 players would stop moving and could only use chat. Sometimes you can see yourself + one other player still moving (can be the enemy or your partner). The match then seems to hand out points rather randomly. Can't pinpoint any trigger for this to happen as it always happened at different stages of the game (mostly after court change though, so maybe that is a lead)

**Comment by sstokic-tgm** [comment]
If this happened in your second match (not first), then it should be fixed with 47c1967 .
If this happened in your first match (but we assume the server crashed by another session), then it should be fixed with 47c1967 .

If this isn't the case, feel free to write feedback!

**Comment by Davingi** [comment]
Closing this issue since the bug doesn't seem to occur anymore.
