### ISSUE TITLE
Getting thrown back in room while playing

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#50]
So, we just randomly got thrown back into the room while we were playing peacefully. I suppose it has something to do with that "backtoroom" code you guys implemented.

**Comment by sstokic-tgm** [comment]
If a player disconnects in the match, you are thrown back to the room. (cause player missing, he would be frozen)

**Comment by Velucy** [comment]
every played was in the room though, nobody was thrown out, we were able to start another game directly after

**Comment by sstokic-tgm** [comment]
Remember, authentication, game and matchplay servers run independently from each other.

If it's an only matchplay disconnect, then its only there. But if the disconnect comes from the game server the user crashes :)

**Comment by Velucy** [comment]
I see, I understand, but when would this be triggered? We all seemed to play normally without any issue, nobody was lagging and I saw nobody disconnecting, would it trigger if someone has no connection to the host for some ms during matchplay?

**Comment by sstokic-tgm** [comment]
No, it gets triggered as soon as the player really disconnects. If he would disconnect in the lobby aswell, then you are thrown back to the room, he would disconnect completly
