### ISSUE TITLE
Tooltips + context menu closing in Pocket

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#51]
Whenever there is some kind of activity in the lobby the tooltip/context menu you have opened inside your Pocket/Shop will close (only my theory on it, as this is less of an issue without a lot of players). I am unsure if this is an issue which was present in the official game in this state, but I am pretty sure it was present when you were inside a chatroom and opened the pocket there.

Low priority stuff, but just wanted to let you know.

**Comment by sstokic-tgm** [comment]
It's because we refresh the lobby by every change that happens inside the lobby.
We will work that one out better in the next time.
