### ISSUE TITLE
Duplicate Item Id on certain items?

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#57]
Currently you're unable to buy "Wood Shelf", "Wood Bookshelf", "Magic Stove", "Red Carpet(Small)", "Red Flower Carpet", "Live Amp", from the shop, or so I thought. But after a server restart I had some of these items in my inventory, but not the amount I bought, rather the gachas I had, became those mentioned items.

For example my Viking gachas got transformed into "Red Carpet(Small)" which gave me 727 of those red carpets, since that was the amount of Viking gachas I had. Some other gacha coins also got transformed, but I can't tell you which those are since I had every gacha coin. See screenshot for what I mean. 

https://imgur.com/a/UGdMnn1

**Comment by sstokic-tgm** [comment]
Does the problem still exists?
This kind of behaviour should happen when the game server is crashing while doing something (in this case buying).

**Comment by Velucy** [comment]
The problem still exists, although a bit differently, you can indeed buy those items I listed, but some other items will transform into them if you have them in your inventory. See the following video for a better explanation. 
https://www.youtube.com/watch?v=Fc0fszig6NM

**Comment by sstokic-tgm** [comment]
Ah, I see thanks.
Don't worry, it's not a bug, just a missing functionality because you are buying from the shops first page / best selling page. Seems like a different packet is sent👍

**Comment by Velucy** [comment]
It happens even if bought from the "gacha tab", the item seems to be in a quantum state (lol) where it decides what it wants to be as soon as you take a look at it. I've had it switch around multiple times, sometimes its the red carpet another time its the viking gacha. I'll try to provide a new video as soon as the server is up again (it just crashed, but not from this experiment i believe).

**Comment by Velucy** [comment]
Alright, I made a new video to show what I mean more clearly:
https://www.youtube.com/watch?v=ALYiOa8RBLc
