### ISSUE TITLE
level 50

### ISSUE THREAD

**Issue by moynmoyn** [sstokic-tgm/JFTSE#60]
yo i know the game crashing  a lot of times and such is more of priority right now but isnt it possible to max the level to 50 right now so the occasional games where it doesnt crash are at least a bit more competetive? (+ would be nice to add more gachas with items that have charge/lob/smash but level 50 would be my main point rn and of course to somehow fix the crashes but ure working on this for sure)

**Comment by sstokic-tgm** [comment]
All are at level 20 already, if 50 or 20 doesn't matter as of matchplay and testing. Level 50 and higher will make more problems with an unfinished server than with a finished server. (From 50+ stat points are handled differently and it has to be done)
