### ISSUE TITLE
Stats Basic Mode

### ISSUE THREAD

**Issue by nahuelorq** [sstokic-tgm/JFTSE#62]
I try playing some matchs, i had 3 wins and when relog it reset to 0 again , i just made this post  to notify.

**Comment by sstokic-tgm** [comment]
0 inside the player info or 0 when starting/ending game?
If 0 inside the player info, then it's because we don't send out that packet yet after logging in to channel (also one of the things I want to do tomorrow) 👍

**Comment by nahuelorq** [comment]
Let me check inside of match, i only saw this inside player info.

**Comment by nahuelorq** [comment]
inside of game is working !

**Comment by sstokic-tgm** [comment]
Fixed with ab38c1402582a0331e03cf8436646efbc83b0050.
If the error still exists, just reopen this issue! :)
