### ISSUE TITLE
Duping Clothes

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#65]
I bought a "Magician Purple Blouse" normally with the "purchase processing" message appearing just like every time and somehow  the item didn't get "blued out" so I went ahead and bought another one, after the second time it got "blued out" so I couldn't buy a third copy. I did the same to the next item "Sweet Violet Blouse". The item after that proceeded to get "blued out" normally. 

I didn't take a look in my pocket after the first time that I bought the clothes, since I didn't wanna miss the opportunity to get a dupe. This happened on my LunLun named "Zoe"

https://imgur.com/a/aO6elno (the full pocket had nothing to do with this, since after the dupe occurred I desperately tried to recreate it buying all kinds of random clothing, which resulted in my full pocket eventually. That's also hinting at the game not crashing as soon as I got those duplicate clothes)

**Comment by sstokic-tgm** [comment]
Not reproducable under normal circumstances. The dupe bug might happen while shopping and the server died in the background.
https://streamable.com/0lfai2

**Comment by sstokic-tgm** [comment]
Does this issue still persist?

**Comment by Velucy** [comment]
I wasn't able to reproduce it.
