### ISSUE TITLE
Define and seperate skill IDs

### ISSUE THREAD

**Issue by Davingi** [sstokic-tgm/JFTSE#66]
// Players Crystals: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
// Quick slot: ?
// Guardian: ? 
// Boss guardians: ?

// 0 = Large red potion, 1 = Large violet potion, 2 = Many meteors
// 3 = Not so many meteors, 4 = Revive, 5 = Souls
// 6 = Make enemy chicken, 7 = Fireball, 8 = Thunder
// 9 = Shield, 10 = Blindness, 11 = Crab, 12 = Blizzard
// 13 = Areafield (has to be activated by players by walking over it)
// 14 = Medusa, 15 = Small red potion, 16 = Middle red potion
// 17 = Gold red potion, 18 = Fking huge red potion
// 19 = Shieldarea (all teammates get shield if in area)
// 20 = Nova = Ball spawning from ground dealing dmg
// (21, 22) = Mole crab (only guardians)
// 23 = Pancake (halloween event) = HEALS HUGE AMOUNT OF LIFE
// (24,29) = Unknown (looks like a stamp)
// 25 = Juice (looks like fireball but with more boom)
// 26 = AoE Thunder (devaberg boss magic)
// 27 = AoE Thunder (atlantis boss magic)
// 28 = Revive icon? But what does it do?
// 30 = ???
// 31 = Multiple multiples (only guardian)
// 32 = Mango juice (AoE heal 300HP)
// 33 = Splash
// 34 = Huge Nova (only guardian) (big nova from hellblod and hera boss of devaberg)
// 35 = Huge holes on ground (only guardian)
// 36 = Crab on fire
// 37 = Time freeze (for boss abttle)
// 38 = Magic potion (reduces cooldown)
// 39 = STR buff, 40 = STA Buff, 41 = DEX Buff, 42 = WIL Buff, 43 = Speedball
// 44 = Charge short speed, 45 = Movement buff, 46 = Ball spin buff,
// 47 = STR AoE, 48 = STA AoE, 49 = DEX AoE, 50 = WIL AoE, 51 = Speedball AoE
// 52 = Charge short speed AoE, 53 = Movement buff AoE, 54 = Ball spin buff AoE
// 55 = Green meteors (hellblood), 56 = Inverts movement
// 57 = Music notes (deactivate all notes on field to deny dmg) (Devaberg guardian)
// (58,59) = New years splash
// 60 = Green holes on ground (only guardian)
// 61 = Spawns crystals on gamefield (Atlantis) (only guardian)
// 62 = Thunders (only guardian)
// 63 = Suspicously normal looking fireball
// 64 = Green lasers (guardian) (dance)

**Comment by nahuelorq** [comment]
**Guardian** : 2 - 5 - 7 - 8 - 10 - 11 - 12 - 14 - 20 -  21 - 22 -56
**Boss Guardian** : 2 - 5 - 7 - 12 - 14 - 20 - 21 22 - 26 - 27 - 34 - 35 - 55 - 60 - 61 - 62 - 64 
**QS**:0 - 2 - 4 - 5 - 6 - 7 - 8 - 9 - 10 - 11- 12- 13 - 14 - 15 - 16 - 17 - 18 - 19 - 20 - 23 - 32 - 
37 - 38 - 39 - 40 - 41 - 42 - 43 - 44- 45 - 46 - 47 - 48 - 49 - 50 - 51 - 52 - 53 - 54 - 

**Spawned Cristals**: 1 - 2 - 3 - 4 (only in 2v2 when ur partner is dead) - 5 - 6 - 7 - 8 - 9- 10  -11 - 12 -
13 - 23 (only in halloween event ) -
