### ISSUE TITLE
21 stat points as level up reward instead of 1

### ISSUE THREAD

**Issue by Vicen1991** [sstokic-tgm/JFTSE#70]
Hello,
my nickname is ViCeN and when I leveled up from lvl 20 to lvl 21 I received 21 stat points to spend instead of 1 point. At first I though it was a problem that everybody had, but then I asked a friend and it didn't happened to him. Now I'm almost level 22 because I want to check if that happens again or not when I level up again. Should I try that? Can my character be fixed? Should I delete my character and create a new one? 

Regards and thank you for your great work.

ViCeN

![21extrapoints](https://user-images.githubusercontent.com/78696524/107153453-f81e0200-696d-11eb-85c9-55925a50eacf.PNG)

**Comment by Andrexo9** [comment]
You didin't use the 20 before

**Comment by Vicen1991** [comment]
Oh, you're right 🤦‍♂️ hahaha I'm dumb ^^" I close the post.
