### ISSUE TITLE
level 50

### ISSUE THREAD

**Issue by moynmoyn** [sstokic-tgm/JFTSE#71]
isnt it possible to just make it level 50? its basically only 1 click for the guy who programms it and it makes the few matches there are a bit more competetive and fun. there is literally no point right now to demand the players to level up as there is not enough players right now. once everything works perfectly without crashes you can always set back the levels and let ppl level up normally but imo right now level 20 makes no sense.

**Comment by Velucy** [comment]
I'll repeat myself here, but eh I'll give you the same answer again.. it's just a testing phase right now, so everything will be reset anyway. Nobody demands of you to level up. If you want to play and have fun this might not be the right time to start playing. You'd probably be better off waiting a bit longer for everything to work properly. Also there are quite a lot of players. The only thing which makes leveling up hard is the crashes.

**Comment by moynmoyn** [comment]
yea but thats not really an argument against level 50? why not just put level 50 i dont see the issue here. "other things have priority" might be true doesnt change the fact u could just put level 50. i still have fun playing even tho it crashes a lot but imo it would just make it more enjoyable right now with higher stats.

**Comment by sstokic-tgm** [comment]
Where is the difference by having all players start at either lvl 1, lvl 20, lvl 50 or either lvl 32?
Where is the difference of the fun level and compentnises between the leveles when everyone starts same? Only that the endgame is 10 lvls apart from it. 

I don't see any difference and I said that in the previous post of you.
For me personally it looks like you only want the corresponding badge for lvl 50 and up when leveled. If you prove me wrong/give me valid/good arguments and I will consider it.

**Comment by osty2021** [comment]
> Where is the difference by having all players start at either lvl 1, lvl 20, lvl 50 or either lvl 32?
> Where is the difference of the fun level and compentnises between the leveles when everyone starts same? Only that the endgame is 10 lvls apart from it?
> 
> I don't see any difference and I said that in the previous post of you.
> For me personally it looks like you only want the corresponding badge for lvl 50 and up when leveled. If you prove me wrong/give me valid/good arguments and I will consider it.

The difference is huge, beetwen 20 - 50 lvl, games are much more faster, and more interesting, peoples can use full potential of them characters.

**Comment by DrBench** [comment]
I think there are more important tasks than putting players at level 50. Besides, the focus should not be on the level, but on the game itself. Be glad that you can play the game again at all. 
Basically, everyone's interest is that game bugs are identified, reported, and corrected.

**Comment by osty2021** [comment]
> I think there are more important tasks than putting players at level 50. Besides, the focus should not be on the level, but on the game itself. Be glad that you can play the game again at all.
> Basically, everyone's interest is that game bugs are identified, reported, and corrected.

I know, i just say that there are huge difference between 20-50 lvls)

**Comment by DrBench** [comment]
Then the case could be closed. Currently, the time should be invested differently.

**Comment by moynmoyn** [comment]
idk what kind of argument this is "be glad that u can play it" according to this logic u can basically remove all clothes and whenever someone says something u just say "yea just be glad u can play it in the first place". "Currently, the time should be invested differently." i mean i dont know shit about programming if u say its so time investing to change level 20 to level 50 or 60 or whatever then yes no need to do it. if its just a simple thing to switch tho imo i dont see a problem not doing it.

@sstokic-tgm saw your respond just now. not sure if u ever played fantasy tennis or how good u were but according to your question i dont think u played it. if u compare a no clothes level 1 match to a full equipped level 60 match its night & day. u do have a lot more opportunities to make points, you have more opportunities to prevent points and so on. sure full equipped level 20 is smthg already its still not the same like have 40 more points in level 60. basically, higher level = mistakes are punished harder so the game gets more intense and competetive.

**Comment by Davingi** [comment]
Since we are in a testing phase we need players in between all type of level ranges to detect other possible bugs. Setting all players to lvl 50 or 60 might even take out the motivation for many players to play since they might miss some goals to reach. Don't take this in a bad way but since this is no bug or feature related thing I'm going to close this issues as this is not in our interest and focus.
