### ISSUE TITLE
Guardian mode

### ISSUE THREAD

**Issue by Davingi** [sstokic-tgm/JFTSE#73]
- [x] Trigger guardian serve
- [x] Spawn guardians
- [x] Set HP for players
- [x] Set HP for guardians
- [x] Deal damage to player
- [x] Deal damage to guardian
- [x] Spawn crystals automatically (currently every 15 seconds)
- [x] Despawn crystals after a while (5 sec despawn)
- [x] Assign skills to player
- [x] Handle use of skills from player
- [x] 10% damage to player if player looses ball
- [x] 2% damage to guardian if guardian looses ball
- [x] Deal correct damage to guardian depending on skill a player uses
- [x] Handle healing items
- [x] Guardians uses skills 
- [x] Change drop rates of skills depending on player level
- [x] Reviving a player
- [x] ~~Revive crystal only 35% chance. When someone dies roll and spawn depending on chance~~ (only battle mode)
- [x] Set correct stats for guardians based on guardian resources
- [x] Fully implement HP for guardians based on information from resource files
- [x] Clean up gamesession properly when guardianmode is done
- [x] Spawn the correct guardians depending on player level and map
- [x] Spawn MonsLavaB dependent on average player level and 25% probability
- [x] Spawn boss battles when guardians are defeated in a certain time range
- [x] Set guardian stats depending on how many players are playing.
- [x] Use bought quick slot skills
- [x] Handle unique items (like sandhour)
- [x] Factor in player stats for skill dmg
- [x] Fully implement HP for players (including cloth stats etc)
- [x] End game (game result window)
- [x] Add chanting for guardians
- [x] Add better logic for which skill a guardian needs to use and which player to target
- [x] Fix that all players can see skills of each other (if one player uses homing soul no other player can see it)
- [x] Fix skill assignment for players
- [x] Fix debuffing skills (Medusa, Burn)
- [x] Finish game with a loose result window if boss defeat timer is at 0 _(dev info: timer starts at first guardian serve after boss animation)_
- [x] Finish game with a loose result window if guardian timer is at 0 (Atlantis) _(dev info: timer starts at first guardian serve)_
- [x] Sandglass should internally (server) increase amount of time left by 60 seconds instead of completely resetting timer + sync increase of time to all players
- [x] Remove 1 skill swapping tool from db for player upon usage
- [x] Display blue dust cloud animation upon crystal pickup
- [x] ~~Item Rewards after game~~ (will be done as a separate issue)

**Comment by milov-afk** [comment]
GoogleSheet to be completed with info for checkpoint "Spawn the correct guardians depending on player level and map"
https://docs.google.com/spreadsheets/d/1q4ZJqeHPHA4e2pXo-FhRQF4goe9WKD3PKmq_wAnzCrw/edit?usp=sharing

**Comment by milov-afk** [comment]
Those are my findings based on the latest updates:
1. collect a crystal>use a QS>spells from crystals get cleared>try to cast a spell(press D)>game crash
2. use a QS>collect a crystal>try to cast a spell(press D)>game crash
3. use a quickslot>try to cast an empty spell(press D)>game crash
4. collect a crystal>try to cast a spell(press D)>spell casted>cast an empty spell(press D)> game crash
QS=Quickslot Spells  spell=Crystal Spell

**Comment by Davingi** [comment]
This is currently caused the way we are using the skill assignment packet. That packet expects that we provide 2 skill ids (for left and right skill slot). Whenever we only want to assign one skill to a player we pass ID -1 for the second skilll slot. While this works visually  it causes the client to crash as soon as you want to use the skill with ID -1. If we find a way to avoid this problem all of your usecases should be fixed in one go.

**Comment by Davingi** [comment]
Closing this issue since the guardian mode is more or less implemented. For future bugs or features new issues should be created
