### ISSUE TITLE
Battle Mode in Single Player isnt working

### ISSUE THREAD

**Issue by ILustu** [sstokic-tgm/JFTSE#8]
![image](https://user-images.githubusercontent.com/68763169/88446777-d1aad600-ce24-11ea-95f3-4334f614301c.png)

Everytime you dmg opponent or win (ie. playing normally) you instantly lose.

**Comment by sstokic-tgm** [comment]
Doing anything or does it happen while playing normal?

**Comment by ILustu** [comment]
> Doing anything or does it happen while playing normal?

Hmmm when I restarted it fixed.

But yes, playing normally was not possible. Thanks for such a quick response. Btw well done for bringing FT back.

**Comment by sstokic-tgm** [comment]
It should be fixed with commit: b9c9fd0
