### ISSUE TITLE
Shields doesn't work in currently guardian-mode branch

### ISSUE THREAD

**Issue by Andrexo9** [sstokic-tgm/JFTSE#80]
Using shield does nothing 
in the console there is the follow error:
WARN  guardianBattleState or playerBattleState is null

**Comment by Andrexo9** [comment]
After looking at code it should be beacuse when using the shield the guardian pos it's null and in the code no matter what if the guardian pos it's null get throwed and the shield doesn't work proprely

**Comment by Davingi** [comment]
Fixed with 309478c8be99a36fbf3516be3c47862277743058
