### ISSUE TITLE
Guardian Mode: Maoi Statue should guard you against damage

### ISSUE THREAD

**Issue by Velucy** [sstokic-tgm/JFTSE#82]
I'm not 100% sure but if I remember this correctly becoming a maoi statue (kiss of medusa QS) should guard you from any incoming damage or reduce incoming damage significantly. Which was why sometimes it was even favorable being a maoi statue, in order to avoid damage from souls/mets, sometimes making you stay in that form for a longer period of time on purpose (briefly stopping to spam left and right in order to get out).

**Comment by Thewimo** [comment]
Agreed and want to confirm this one too.
