### ISSUE TITLE
Item Re-Status

### ISSUE THREAD

**Issue by toddymon** [sstokic-tgm/JFTSE#89]
Can we fix this item for re-status of character.
For now we use this then that wasn't happening.
![image](https://user-images.githubusercontent.com/26331241/111902264-32031d80-8a6f-11eb-843e-b5295ab794eb.png)

**Comment by sstokic-tgm** [comment]
Duplicate of #24
Item behaviour items are further down in the prio list, they will come after the basic/general game functionality is brought back 👍

**Comment by toddymon** [comment]
Thanks. *-*
