### ISSUE TITLE
Multiple errors appear!

### ISSUE THREAD

**Issue by jcs090218** [sstokic-tgm/JFTSE#9]
I have cloned from master branch yet there are multiple errors like `accountHome.getBasicBonusGold()` the method `getBasicBonusGold` doesn't exists. I believed there are something that are not commit to git? 

Just wondering! Thanks! 😄

**Comment by sstokic-tgm** [comment]
I think you are using eclipse or?
Well it's just due to lombok lib.

https://www.baeldung.com/lombok-ide

**Comment by jcs090218** [comment]
I am using Intellij, I think that's what you are using? 😕 

Solved by installed lombok plugin from marketplace! Thanks! 😄 

Anyway, I was expecting the Intellij will installs it on it's own. 😕 😕

**Comment by sstokic-tgm** [comment]
Ah nice, yeah I also use IntelliJ.
Seems like I did that in the past and forgot about it. Though maven still downloads the dependency for compile via CLI :)

Glad it works now! :)
