### ISSUE TITLE
Inventory bug for QS and clothes

### ISSUE THREAD

**Issue by G1i2o3** [sstokic-tgm/JFTSE#90]
When you buy QS or clothes, items on inventory could be deleted and replaced with new item buyed.
Example: you have 1000shields. Buy crabs on shop, you will now have 1050 crabs and no shields.

I notice that if you relog, bug fixes itself sometimes.

**Comment by sstokic-tgm** [comment]
I think this bug is already defined somewhere here, but eitherway, so you are saying:
-) Buy Shields
-) Buy Crabs
-) Then you relog and the items transformmed

Is that right? Or you generally mean that items get transformed into others?

**Comment by G1i2o3** [comment]
It's more complicated, maybe there are two or more bugs... 
I've seen that if I buy shields (or other QS) for 20-30 times and then I buy crabs, they count like I buy other shields.
Sometimes, if I relog items are transformed, even if last time I just played and didn't buy anything.
