### ISSUE TITLE
(Code = 4002, -62)

### ISSUE THREAD

**Issue by oleksandr007** [sstokic-tgm/JFTSE#93]
"You have been disconnected because you tried to connect with an old version. Application will now shut down." Im not able to log in. It doesn't matter what password it is, always the same massage! I'm starting always with FT_Launcher.

**Comment by sstokic-tgm** [comment]
Does it still exist? The problem was a thing last weeks ago, but shouldn't be there anymore :)

**Comment by oleksandr007** [comment]
The problem is solved solved! Visual C++ 2015 the x86 Version needs to be installed.

**Comment by sstokic-tgm** [comment]
Super, then I close it! 😄
